lesson_12/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from market import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('user/', include('user.urls')),
    #*staticfiles_urlpatterns(),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

]

market/urls.py
from django.urls import path

from market import views
from market.views import ItemView, WallpapersView, WallpaperItemView, WallpaperCreateView

app_name = 'market'

urlpatterns = [
    path('', WallpapersView.as_view(), name='list'),
    path('view/<item_id>/', WallpaperItemView.as_view(), name='item'),
    path('add/', WallpaperCreateView.as_view(), name='add'),
    path('wallpaper/<item_id>/edit', views.update, name='edit'),
    path('wallpaper/<item_id>/', ItemView.as_view(), name='wallpaper'),
]

user/urls.py
from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup')
]

market/models.py
from datetime import date

from django.db import models
from django.contrib.auth.models import User



class Brand(models.Model):
    name = models.CharField(max_length=50)
    rating = models.FloatField(max_length=5)

    def __str__(self):
        return f'{self.pk}-{self.name}({self.rating})'


class Tags(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return str(self.name)


class Wallpaper(models.Model):
    slug = models.SlugField(unique=True, allow_unicode=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=50)
    price = models.FloatField(null=True, blank=True)
    available = models.BooleanField(default=False)
    quantity = models.IntegerField(default=0)
    description = models.TextField()
    cover = models.ImageField(blank=True, null=True, default='placeholder.png')
    tags = models.ManyToManyField(Tags)
    creator = models.ForeignKey(User, null=True, blank=True, default=None, on_delete=models.SET_NULL)
    create_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

    class Meta:
        ordering = ['price', 'create_at']

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('market:item', kwargs={'item_id': self.slug})

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.slug:
            self.slug = f'{str(self.name).lower().replace(" ", "-").replace("/", "-")[:20]}-{self.color}'
        super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return f'{self.pk} - {self.brand} - {self.name}'

market/forms.py
from django import forms

from market.models import Wallpaper


class WallpaperForm(forms.ModelForm):
    class Meta:
        model = Wallpaper
        fields = ('name', 'brand', 'tags', 'color', 'price', 'available', 'quantity', 'description', 'cover')

market/views.py
import logging

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, FormView

from market.forms import WallpaperForm
from market.models import Wallpaper


logger = logging.getLogger('MarketView')


@permission_required(perm='market.view_wallpaper')
def list(request):
    wallpapers = Wallpaper.objects.all()
    return render(request,
                  'market/wallpapers.html',
                  context={'wallpapers': wallpapers, 'injected_text': '<script>alert("FAA")</script>'})


@login_required
def item(request, item_id):
    wallpaper = Wallpaper.objects.get(slug=item_id)  # Compiled to Select * from wallppaper where slug=:item_id
    tags = wallpaper.tags.all()
    return render(request,
                  'market/wallpaper.html',
                  context={'wallpaper': wallpaper, 'tags': tags})


@staff_member_required
def add(request):
    if request.method == 'POST':
        form = WallpaperForm(request.POST, request.FILES)
        if form.is_valid():
            new_wallpaper = form.save(commit=False)
            new_wallpaper.creator = request.user
            new_wallpaper.save()
            form.save_m2m()
            return redirect('market:item', item_id=new_wallpaper.slug)
        return render(request, 'market/new_wallpaper.html', context={'form': form})
    form = WallpaperForm()
    return render(request, 'market/new_wallpaper.html', context={'form': form})


@login_required
def update(request, item_id):
    wallpaper = Wallpaper.objects.get(slug=item_id)
    form = WallpaperForm(instance=wallpaper)
    return render(request,
                  'market/edit_wallpaper.html',
                  context={'form': form, 'slug': item_id})


class ItemView(View):
    def get(self, request, item_id):
        wallpaper = Wallpaper.objects.get(slug=item_id)
        tags = wallpaper.tags.all()
        return render(request,
                      'market/wallpaper.html',
                      context={'wallpaper': wallpaper, 'tags': tags})

    def post(self, request, item_id):
        wallpaper = Wallpaper.objects.get(slug=item_id)
        form = WallpaperForm(request.POST, request.FILES, instance=wallpaper)
        if form.is_valid():
            form.save()
            return redirect('market:wallpaper', item_id=item_id)
        return redirect('market:edit', item_id=item_id)


class WallpapersView(ListView):
    model = Wallpaper
    ordering = '-name'

    def get_ordering(self):
        return self.request.GET.get('orderBy', self.ordering)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['injected_text'] = 'You\'ve been hacked'
        return context


class WallpaperItemView(DetailView):
    model = Wallpaper
    slug_url_kwarg = 'item_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.object:
            context['tags'] = self.object.tags.all()
        return context


class WallpaperAddFormView(FormView):
    template_name = 'market/new_wallpaper.html'
    form_class = WallpaperForm

    def form_valid(self, form):
        new_wallpaper = form.save(commit=False)
        new_wallpaper.creator = self.request.user
        new_wallpaper.save()
        form.save_m2m()
        return redirect('market:item', item_id=new_wallpaper.slug)


class WallpaperCreateView(LoginRequiredMixin, CreateView):
    model = Wallpaper
    form_class = WallpaperForm

    def form_valid(self, form):
        new_wallpaper = form.save(commit=False)
        new_wallpaper.creator = self.request.user
        new_wallpaper.save()
        form.save_m2m()
        return super().form_valid(form)

market/templates/market/edit_wallpaper.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
    <link rel="stylesheet" type="text/css" href="{% static 'market/style.css' %}">
{% endblock %}

{% block content %}
<form class="section" action="{% url 'market:wallpaper' item_id=slug %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Змінити">
</form>
{% endblock %}

market/templates/market/new_wallpaper.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
    <link rel="stylesheet" type="text/css" href="{% static 'market/style.css' %}">
{% endblock %}

{% block content %}
<form class="section" action="{% url 'market:add' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Додать">
</form>
{% endblock %}

market/templates/market/wallpaper.html
{% extends 'base.html' %}


{% block content %}
<a href="{% url 'market:list' %}"><- Return</a>

<h1>Id: {{ wallpaper.pk }}</h1>
<h1>Name: {{ wallpaper.name }}</h1>
<h2>Brand: {{ wallpaper.brand.name }}</h2>
<h3>Price: {{ wallpaper.price }}</h3>
<h3>Added: {{ wallpaper.create_at }}</h3>

<h3>Характеристики: </h3>
{% if tags %}
<ul>
    {% for tag in tags %}
    <li id="{{tag.name}}-{{tag.pk}}">{{tag.name}}</li>
    {% endfor %}
</ul>
{% else %}
<p>відсутні</p>
{% endif %}
<img src="{{ wallpaper.cover.url }}"/>
{% endblock %}

market/templates/market/wallpaper_detail.html
{% extends 'base.html' %}


{% block content %}
<a href="{% url 'market:list' %}"><- Return</a>

<h1>Id: {{ wallpaper.pk }}</h1>
<h1>Name: {{ wallpaper.name }}</h1>
<h2>Brand: {{ wallpaper.brand.name }}</h2>
<h3>Price: {{ wallpaper.price }}</h3>
<h3>Added: {{ wallpaper.create_at }}</h3>

<h3>Характеристики: </h3>
{% if tags %}
<ul>
    {% for tag in tags %}
    <li id="{{tag.name}}-{{tag.pk}}">{{tag.name}}</li>
    {% endfor %}
</ul>
{% else %}
<p>відсутні</p>
{% endif %}
<img src="{{ wallpaper.cover.url }}"/>
{% endblock %}

market/templates/market/wallpaper_form.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
    <link rel="stylesheet" type="text/css" href="{% static 'market/style.css' %}">
{% endblock %}

{% block content %}
<form class="section"  method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Додать">
</form>
{% endblock %}

market/templates/market/wallpaper_list.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
    <link rel="stylesheet" type="text/css" href="{% static 'market/style.css' %}">
{% endblock %}

{% block content %}
<mycustomtag>{{ injected_text }}</mycustomtag>
<div class="header">
    <h1>Шпялєри</h1>
    <div id="counter" class="green" style="color: #6f42c1;">{{ wallpapers|length }} wallpapers found</div>
</div>

<div class="catalog">
    {% for wallpaper in wallpaper_list %}
        <div class="section">

            <a class="item" href="{{ wallpaper.get_absolute_url }}">{{wallpaper.name}}</a>
            <img src="{{wallpaper.cover.url}}">
            {% if wallpaper.price %}
            <p>
                Ціна: <span>{{wallpaper.price}}</span><span class="currency">!TEXT!</span>
            </p>
            {% else %}
                <div>Товар продано <span>&#128169</span></div>
            {% endif %}
        </div>
    {% endfor %}
</div>
{% endblock %}

market/templates/market/wallpapers.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
    <link rel="stylesheet" type="text/css" href="{% static 'market/style.css' %}">
{% endblock %}

{% block content %}
<mycustomtag>Some text</mycustomtag>
<div class="header">
    <h1>Шпялєри</h1>
    <div id="counter" class="green" style="color: #6f42c1;">{{ wallpapers|length }} wallpapers found</div>
</div>

<div class="catalog">
    {% for wallpaper in wallpapers %}
        <div class="section">

            <a class="item" href="{{ wallpaper.get_absolute_url }}">{{wallpaper.name}}</a>
            <img src="{{wallpaper.cover.url}}">
            {% if wallpaper.price %}
            <p>
                Ціна: <span>{{wallpaper.price}}</span><span class="currency">!TEXT!</span>
            </p>
            {% else %}
                <div>Товар продано <span>&#128169</span></div>
            {% endif %}
        </div>
    {% endfor %}
</div>
{% endblock %}